### ISSUE TITLE
Error on creating a new account on 139-get-access-operations

### ISSUE THREAD

**Issue by hiyaryan** [cognovi-ai/the-cdj#211]
When a user signs up for beta access, they must verify their email address using a tokenized link sent to their inbox. They then wait for an approval email with a new tokenized link to reset their password. The following error is being returned from the server,

`Password reset token is invalid or has expired.`

This error is occurring on branch `139-get-access-operations` which is being merged into `139-ts-migration` in PR #194. `139-ts-migration` has been tested and account creation is possible as expected.

It is difficult to test account creation in beta because it requires setting up an SMPT server making it easy to introduce a bug without thoroughly manually testing it. Unit tests may not be useful here because it requires checking the token in the session store, so integration testing may be more appropriate here even if SMPT is mocked.

**Comment by hiyaryan** [comment]
@davidzlu, I have SMPT set up so I will work on resolving this bug and will push a fix to your branch `139-get-access-operations`. Might you know what changes were made that could have introduced the bug so I can try to isolate it more effectively? I haven't looked at the `/register` route yet because I'm reviewing everything else that seems to be working provided an account already exists.

**Comment by davidzlu** [comment]
Looks like it's line 393 of the access controller `await AccountServices.resetPassword(newPassword, token);`. The arguments are in the wrong order. It should be `await AccountServices.resetPassword(token, newPassword);`

**Comment by hiyaryan** [comment]
@davidzlu Seems like an easy enough fix. You're welcome to make that fix and push it up. Then I can test out account creation on my end.

**Comment by davidzlu** [comment]
> @davidzlu Seems like an easy enough fix. You're welcome to make that fix and push it up. Then I can test out account creation on my end.

I pushed the commit with the fix

**Comment by hiyaryan** [comment]
> > @davidzlu Seems like an easy enough fix. You're welcome to make that fix and push it up. Then I can test out account creation on my end.
> 
> I pushed the commit with the fix

That fixed it! Thank you @davidzlu 🙌
